#!/bin/bash
# fsc-typing-test.sh — FolderTest keyboard typing E2E (every table row) on an isolated instance (Issue245)
#
# Real key input -> CGEventTap -> expansion -> pasted text, for every row of
# cli/fSnippetCliTests/FolderTest/testTable_org.md. The fixtures (_rule.yml and
# _case<N>/<key>===case<N>.txt) are generated here into the isolated test root, so
# the run needs no hand-made data and never touches the user's data root, :3015
# or the brew service.
#
# Usage: ./fsc-typing-test.sh [--no-build] [--case N] [--no-fixture]
#   --no-build    reuse the last Debug build (fsc-run-xcode.sh deploy-run)
#   --case N      run only case N (passed through to qa/qa_run_batch.sh)
#   --no-fixture  skip fixture generation (red check: proves a missing fixture fails)
#
# Steps:
#   0  stop the previous test instance (the brew/user instance is left alone)
#   1  reset the isolated test root snippets + test prefs
#   2  generate fixtures from testTable_org.md
#   3  launchctl setenv + build/deploy/run the isolated instance
#   4  REST health + rule check: every _case folder loaded with the table's prefix/suffix
#   5  qa/qa_run_batch.sh (typing harness)
#   6  launchctl unsetenv + stop the test instance
#
# Exit status: 0 only when every step and every case passed.
# Shares TEST_ROOT / port / isolation with fsc-test.sh (prj5#Issue99) — both reset
# snippets/ on every run, so they do not leak fixtures into each other.

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLI_DIR="$(dirname "$SCRIPT_DIR")"
RUN_XCODE="$SCRIPT_DIR/fsc-run-xcode.sh"
TABLE="$CLI_DIR/fSnippetCliTests/FolderTest/testTable_org.md"
TEST_ROOT="$HOME/Documents/finfra/fSnippetData_testForCli"
export FSC_API_PORT="${FSC_API_PORT:-3115}"
export fSnippetCli_config="$TEST_ROOT"
export fSnippetCli_isolated=1

BUILD_CMD="build-deploy"
ONLY_CASE=""
MAKE_FIXTURE=1
while [ $# -gt 0 ]; do
    case "$1" in
        --no-build)   BUILD_CMD="deploy-run"; shift ;;
        --case)       ONLY_CASE="$2"; shift 2 ;;
        --no-fixture) MAKE_FIXTURE=0; shift ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

# shellcheck source=fsc-config.sh
source "$SCRIPT_DIR/fsc-config.sh"

cleanup() {
    launchctl unsetenv fSnippetCli_config
    launchctl unsetenv fSnippetCli_isolated
    pkill -f "$(fsc_kill_pattern)"
}

fail_out() {
    echo "❌ $1"
    cleanup
    exit 1
}

echo "╔══════════════════════════════════════════╗"
echo "║   fSnippetCli FolderTest Typing E2E      ║"
echo "╚══════════════════════════════════════════╝"
[ -f "$TABLE" ] || fail_out "testTable not found: $TABLE"

# --- Step 0 ---
echo "=== Step 0: 이전 테스트 인스턴스 종료 ==="
pkill -f "$(fsc_kill_pattern)"
sleep 1
if curl -s -m 2 "http://localhost:3015/" >/dev/null; then
    # The user instance also watches the keyboard. Its own snippets could react to
    # the typed abbreviations — report it so a mismatch is not misread as an engine bug.
    echo "ℹ️ :3015 사용자 인스턴스 실행 중 — 격리 인스턴스와 함께 키 입력을 본다"
fi

# --- Step 1 ---
echo "=== Step 1: 격리 테스트 루트 초기화 ($TEST_ROOT) ==="
case "$TEST_ROOT" in
    */fSnippetData_testForCli) rm -rf "$TEST_ROOT/snippets" ;;
    *) fail_out "예상 밖 TEST_ROOT: $TEST_ROOT — 초기화 거부" ;;
esac
mkdir -p "$TEST_ROOT/snippets" "$TEST_ROOT/logs" || fail_out "테스트 루트 생성 실패"
set_test_pref() {
    local key="$1" value="$2" cfg="$TEST_ROOT/_config.yml"
    [ -f "$cfg" ] || printf 'preferences:\n' > "$cfg"
    if grep -qE "^[[:space:]]*${key}:" "$cfg"; then
        sed -i '' -E "s|^([[:space:]]*${key}:).*|\1 ${value}|" "$cfg"
    else
        sed -i '' -E "s|^preferences:$|preferences:\\
  ${key}: ${value}|" "$cfg"
    fi
}
set_test_pref api_port "$FSC_API_PORT"
set_test_pref snippet_trigger_key '"{right_command}"'
set_test_pref log_level '"DEBUG"'

# --- Step 2 ---
echo "=== Step 2: 픽스처 생성 ==="
if [ "$MAKE_FIXTURE" -eq 1 ]; then
    # Same _rule.yml shape as FolderRuleTableTests (unquoted name, single-quoted values,
    # empty prefix/suffix omitted). One file per case folder, keyed by the table's
    # key column (`test`, or `ant` for case39); the content is
    # unique per case so a wrong-folder expansion is caught by the comparison.
    python3 - "$TABLE" "$TEST_ROOT/snippets" <<'PY' || fail_out "픽스처 생성 실패"
import os, sys
table, root = sys.argv[1], sys.argv[2]
rows = []
for line in open(table, encoding="utf-8"):
    if not line.startswith("|"):
        continue
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    if len(cells) < 6 or not cells[0].isdigit():
        continue
    keys = [k.strip() for k in cells[3].split(",")]
    rows.append((int(cells[0]), cells[1], cells[2], cells[4], keys[-1]))
if not rows:
    sys.exit("no case rows in " + table)
yaml = ["# Auto-generated by fsc-typing-test.sh from testTable_org.md", "collections:"]
for cid, folder, prefix, suffix, _ in rows:
    if not prefix and not suffix:
        continue
    yaml.append(f"  - name: {folder}")
    if prefix:
        yaml.append(f"    prefix: '{prefix}'")
    if suffix:
        yaml.append(f"    suffix: '{suffix}'")
    yaml.append("")
with open(os.path.join(root, "_rule.yml"), "w", encoding="utf-8") as f:
    f.write("\n".join(yaml) + "\n")
for cid, folder, prefix, suffix, keyword in rows:
    d = os.path.join(root, folder)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, f"{keyword}===case{cid}.txt"), "w", encoding="utf-8") as f:
        f.write(f"QA-case{cid}-expanded")
print(f"fixtures: {len(rows)} cases -> {root}")
PY
else
    echo "⚠️ --no-fixture — 픽스처 생략 (red 확인용)"
fi

# --- Step 3 ---
echo "=== Step 3: 격리 인스턴스 기동 ($BUILD_CMD, :$FSC_API_PORT) ==="
launchctl setenv fSnippetCli_config "$TEST_ROOT"
launchctl setenv fSnippetCli_isolated 1
bash "$RUN_XCODE" "$BUILD_CMD" || fail_out "빌드·배포·실행 실패 ($BUILD_CMD)"

# --- Step 4 ---
echo "=== Step 4: REST 응답 + 규칙 로드 확인 ==="
HEALTH=""
for _i in $(seq 1 20); do
    HEALTH="$(curl -s -m 2 "http://localhost:$FSC_API_PORT/")"
    [ -n "$HEALTH" ] && break
    sleep 1
done
[ -n "$HEALTH" ] || fail_out "20초 내 :$FSC_API_PORT 응답 없음"
if [ "$MAKE_FIXTURE" -eq 1 ]; then
    # stdin carries the script (heredoc), so the JSON goes through the environment.
    FOLDERS_JSON="$(curl -s -m 5 "http://localhost:$FSC_API_PORT/api/v2/folders?limit=1000")" \
        python3 - "$TABLE" <<'PY' || fail_out "격리 인스턴스가 픽스처 규칙을 표와 다르게 로드함"
import json, os, sys
table = sys.argv[1]
want = {}
for line in open(table, encoding="utf-8"):
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    if line.startswith("|") and len(cells) >= 6 and cells[0].isdigit():
        want[cells[1]] = (cells[2], cells[4])
got = {f["name"]: (f.get("prefix", ""), f.get("suffix", ""))
       for f in json.loads(os.environ["FOLDERS_JSON"] or "{}").get("data", [])
       if f.get("name") in want}
bad = [f"{n}: want {w} got {got.get(n)}" for n, w in want.items() if got.get(n) != w]
for b in bad:
    print("  ❌", b)
print(f"  rule check: {len(want) - len(bad)}/{len(want)} folders match the table")
sys.exit(1 if bad else 0)
PY
fi

# --- Step 5 ---
echo "=== Step 5: 타이핑 배치 ==="
BATCH_ARGS=("$TABLE")
[ -n "$ONLY_CASE" ] && BATCH_ARGS+=(--case "$ONLY_CASE")
bash "$SCRIPT_DIR/qa/qa_run_batch.sh" "${BATCH_ARGS[@]}"
BATCH_RC=$?

# --- Step 6 ---
echo "=== Step 6: 환경 원복 ==="
cleanup
echo "fSnippetCli_config·fSnippetCli_isolated 해제 · 테스트 인스턴스 종료"

if [ "$BATCH_RC" -eq 0 ]; then
    echo "🎉 TYPING E2E PASS"
else
    echo "❌ TYPING E2E FAIL (qa_run_batch rc=$BATCH_RC)"
fi
exit "$BATCH_RC"
