# fSnippet Configuration
# Created: 2026-04-17 04:46:04 +0000

preferences:
  alfred_import_source_path: "/tmp/test.alfdb"
  api_allow_external: false
  api_allowed_cidr: "127.0.0.1/32"
  api_enabled: true
  api_port: 3015
  appearance_mode: "system"
  cursor_max_distance: 200
  force_search_input_language: "U.S."
  hide_menu_bar_icon: false
  history.enable.fileLists: true
  history.enable.images: true
  history.enable.plainText: true
  history.forceInputSource: "com.apple.keylayout.US"
  history.ignore.fileLists: true
  history.ignore.images: false
  history.imageDetail.isFloating: false
  history.integrate.showSnippetsInSearch: false
  history.integrate.snippetsHeader: false
  history.isPaused: false
  history.moveDuplicatesToTop: true
  history.pause.hotkey: "{^⌥⌘P}"
  history.pause.showNotification: true
  history.preview.hotkey: ""
  history.preview.width: 400
  history.registerSnippet.hotkey: "{⌘S}"
  history.retentionDays.fileLists: 30
  history.retentionDays.images: 7
  history.retentionDays.plainText: 90
  history.showPreview: true
  history.showStatusBar: true
  history.viewer.hotkey: "{⌘;}"
  history.viewer.width: 350
  history.viewer_preview.width: 400
  key_logging: false
  language: "en"
  log_level: "info"
  performance.key_buffer_size: 200
  performance_monitoring: false
  play_ready_sound: true
  settings.hotkey: "^⇧⌘;"
  show_in_app_switcher: true
  show_notifications: true
  snippet_base_path: "./snippets"
  snippet_excluded_files:
    ["README.md", "_README.md", "z_old", ".gitignore", ".DS_Store"]
  snippet_folder_excluded_files: {}
  snippet_folder_openable._emoji: true
  snippet_last_selected_folder: "_symbol_space"
  snippet_list_abbr_width: 111.1328125
  snippet_list_name_width: 81.23828125
  snippet_popup_height: 300
  snippet_popup_hotkey: "⌃⇧Space"
  snippet_popup_key_code: 49
  snippet_popup_modifier_flags: 393475
  snippet_popup_preview_width: 400
  snippet_popup_quick_select_modifier_flags: 1048576
  snippet_popup_rows: 8
  snippet_popup_search_scope: "content"
  snippet_popup_width: 500
  snippet_stats_retention_months: 1
  snippet_stats_retention_usage_days: 30
  snippet_trigger_bias: 0
  snippet_trigger_key: "{right_command}"
  start_at_login: true
